################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
obj/local/armeabi/objs/game_shared/hellocpp \
obj/local/armeabi/objs/game_shared/__/__/Classes \
obj/local/armeabi/objs/game_shared/__/__/Classes/Level \
obj/local/armeabi/objs/game_shared/__/__/Classes/Level/Rider \
obj/local/armeabi/objs/game_shared/__/__/Classes/Level/Objects \
obj/local/armeabi/objs/game_shared/__/__/Classes/Level/Backgrounds \
obj/local/armeabi/objs/game_shared/__/__/Classes/FrontEnd \
obj/local/armeabi/objs/game_shared/__/__/Classes/FrontEnd/Store \
obj/local/armeabi/objs/game_shared/__/__/Classes/Commercials \
obj/local/armeabi/objs/cocosdenshion_static/opensl \
obj/local/armeabi/objs/cocosdenshion_static/jni \
obj/local/armeabi/objs/cocosdenshion_static \
obj/local/armeabi/objs/cocos_extension_static/physics_nodes \
obj/local/armeabi/objs/cocos_extension_static/network \
obj/local/armeabi/objs/cocos_extension_static/LocalStorage \
obj/local/armeabi/objs/cocos_extension_static/GUI/CCScrollView \
obj/local/armeabi/objs/cocos_extension_static/GUI/CCEditBox \
obj/local/armeabi/objs/cocos_extension_static/GUI/CCControlExtension \
obj/local/armeabi/objs/cocos_extension_static/CCBReader \
obj/local/armeabi/objs/cocos2dx_static/touch_dispatcher \
obj/local/armeabi/objs/cocos2dx_static/tilemap_parallax_nodes \
obj/local/armeabi/objs/cocos2dx_static/textures \
obj/local/armeabi/objs/cocos2dx_static/text_input_node \
obj/local/armeabi/objs/cocos2dx_static/support/zip_support \
obj/local/armeabi/objs/cocos2dx_static/support/image_support \
obj/local/armeabi/objs/cocos2dx_static/support/data_support \
obj/local/armeabi/objs/cocos2dx_static/support \
obj/local/armeabi/objs/cocos2dx_static/sprite_nodes \
obj/local/armeabi/objs/cocos2dx_static/shaders \
obj/local/armeabi/objs/cocos2dx_static/script_support \
obj/local/armeabi/objs/cocos2dx_static/platform \
obj/local/armeabi/objs/cocos2dx_static/platform/android/jni \
obj/local/armeabi/objs/cocos2dx_static/platform/android \
obj/local/armeabi/objs/cocos2dx_static/particle_nodes \
obj/local/armeabi/objs/cocos2dx_static/misc_nodes \
obj/local/armeabi/objs/cocos2dx_static/menu_nodes \
obj/local/armeabi/objs/cocos2dx_static/layers_scenes_transitions_nodes \
obj/local/armeabi/objs/cocos2dx_static/label_nodes \
obj/local/armeabi/objs/cocos2dx_static/keypad_dispatcher \
obj/local/armeabi/objs/cocos2dx_static/kazmath/src \
obj/local/armeabi/objs/cocos2dx_static/kazmath/src/GL \
obj/local/armeabi/objs/cocos2dx_static/effects \
obj/local/armeabi/objs/cocos2dx_static/draw_nodes \
obj/local/armeabi/objs/cocos2dx_static \
obj/local/armeabi/objs/cocos2dx_static/cocoa \
obj/local/armeabi/objs/cocos2dx_static/base_nodes \
obj/local/armeabi/objs/cocos2dx_static/actions \
obj/local/armeabi/objs/chipmunk_static/src \
obj/local/armeabi/objs/chipmunk_static/src/constraints \
obj/local/armeabi/objs/box2d_static/Rope \
obj/local/armeabi/objs/box2d_static/Dynamics \
obj/local/armeabi/objs/box2d_static/Dynamics/Joints \
obj/local/armeabi/objs/box2d_static/Dynamics/Contacts \
obj/local/armeabi/objs/box2d_static/Common \
obj/local/armeabi/objs/box2d_static/Collision \
obj/local/armeabi/objs/box2d_static/Collision/Shapes \
jni/hellocpp \
Clibs/extensions/physics_nodes \
Clibs/extensions/network \
Clibs/extensions/LocalStorage \
Clibs/extensions/GUI/CCScrollView \
Clibs/extensions/GUI/CCEditBox \
Clibs/extensions/GUI/CCControlExtension \
Clibs/extensions/CCBReader \
Clibs/cocos2dx/touch_dispatcher \
Clibs/cocos2dx/tilemap_parallax_nodes \
Clibs/cocos2dx/textures \
Clibs/cocos2dx/text_input_node \
Clibs/cocos2dx/support/zip_support \
Clibs/cocos2dx/support/image_support \
Clibs/cocos2dx/support/data_support \
Clibs/cocos2dx/support \
Clibs/cocos2dx/sprite_nodes \
Clibs/cocos2dx/shaders \
Clibs/cocos2dx/script_support \
Clibs/cocos2dx/platform \
Clibs/cocos2dx/platform/ios \
Clibs/cocos2dx/platform/android/jni \
Clibs/cocos2dx/platform/android \
Clibs/cocos2dx/particle_nodes \
Clibs/cocos2dx/misc_nodes \
Clibs/cocos2dx/menu_nodes \
Clibs/cocos2dx/layers_scenes_transitions_nodes \
Clibs/cocos2dx/label_nodes \
Clibs/cocos2dx/keypad_dispatcher \
Clibs/cocos2dx/kazmath/src \
Clibs/cocos2dx/kazmath/src/GL \
Clibs/cocos2dx/effects \
Clibs/cocos2dx/draw_nodes \
Clibs/cocos2dx \
Clibs/cocos2dx/cocoa \
Clibs/cocos2dx/base_nodes \
Clibs/cocos2dx/actions \
Clibs/CocosDenshion/android/opensl \
Clibs/CocosDenshion/android/jni \
Clibs/CocosDenshion/android \
Clibs/Box2D/Rope \
Clibs/Box2D/Dynamics \
Clibs/Box2D/Dynamics/Joints \
Clibs/Box2D/Dynamics/Contacts \
Clibs/Box2D/Common \
Clibs/Box2D/Collision \
Clibs/Box2D/Collision/Shapes \
Classes \
Classes/Level \
Classes/Level/Rider \
Classes/Level/Objects \
Classes/Level/Backgrounds \
Classes/FrontEnd \
Classes/FrontEnd/Store \
Classes/Commercials \

